name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:  # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Omijeh-David
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
