name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:  # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: tech-monarch
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
          color_snake: "#9b5de5"  # nice purple color
          color_dots: "#5a189a, #7b2cbf, #9d4edd, #c77dff"  # shades of purple

      - name: push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
